FROM mcr.microsoft.com/playwright/python:v1.62.0-jammy
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the backend code
COPY . .

# Start FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]
